import { test, expect } from '@playwright/test'

import { LoginPage } from '../pages/LoginPage'
import { DashboardPage } from '../pages/DashboardPage'
import { UserManagementPage } from '../pages/UserManagementPage'
import { PIMPage } from '../pages/PIMPage'
import { RecruitmentPage } from '../pages/RecruitmentPage'
import { CandidatePage } from '../pages/CandidatePage'

import path from 'node:path'
import { fileURLToPath } from 'node:url'


test('TC05 - Verify employee can be associated with a system user, vacancy, and candidate', async ({ page }) => {

    test.setTimeout(120000)

    // Page objects
    const loginPage = new LoginPage(page)
    const dashboardPage = new DashboardPage(page)
    const pimPage = new PIMPage(page)
    const userManagementPage = new UserManagementPage(page)
    const recruitmentPage = new RecruitmentPage(page)
    const candidatePage = new CandidatePage(page)

    // --------------------------------------------------
    // Test data for creating a new Admin user
    // --------------------------------------------------
    const firstName = 'Milo'
    const middleName = 'QE'
    const lastName = `T${Date.now().toString().slice(-3)}`
    const employeeName = `${firstName} ${middleName} ${lastName}`

    const username = `e2e_user_${Date.now().toString().slice(-5)}`
    const password = `#Admin123@`

    const employeeDisplayName = `${firstName} ${lastName}`

    const vacancyName = `QA Vacancy ${Date.now().toString().slice(-6)}`
    const jobTitle = 'QA Engineer'
    const description = 'E2E vacancy created for automation testing.'
    const numberOfPositions = 1


    // --------------------------------------------------
    // Test data for creating a new Candidate
    // --------------------------------------------------
    const candidateFirstName = 'Milo'
    const candidateMiddleName = 'QE'
    const candidateLastName = `Candidate${Date.now().toString().slice(-4)}`
    const candidateName = `${candidateFirstName} ${candidateMiddleName} ${candidateLastName}`

    const candidateEmail = `milo.qe.${Date.now().toString().slice(-4)}@gmail.com`

    const currentFile = fileURLToPath(import.meta.url)
    const currentDirectory = path.dirname(currentFile)
    const resumePath = path.resolve(currentDirectory, '../fixtures/testResumeFile.txt')


    // =========================
    // Login
    // =========================
    await page.goto('/', { waitUntil: 'domcontentloaded', timeout: 30000 })

    await loginPage.login('Admin', 'admin123')

    await expect(dashboardPage.dashboardHeading).toBeVisible()


    // =========================
    // PIM - Create Employee
    // =========================
    await pimPage.navigateToPIM()

    await expect(pimPage.pimHeading).toHaveText('PIM')

    await pimPage.navigateToAddEmployee()

    await pimPage.addNewEmployee(firstName, middleName, lastName)

    // Capture Employee ID generated by OrangeHRM
    const generatedEmployeeId = await pimPage.getEmployeeId()


    // =========================
    // PIM - Retrieve Employee
    // =========================
    await pimPage.navigateToEmployeeList()

    await pimPage.searchEmployeeById(generatedEmployeeId)

    const newlyAddedEmployeeRow = await pimPage.findEmployeeById(generatedEmployeeId)

    expect(newlyAddedEmployeeRow).not.toBeNull()

    await expect(newlyAddedEmployeeRow).toBeVisible()


    // =========================
    // Admin - User Management
    // =========================
    await dashboardPage.navigateToAdmin()


    // -------------------------------------------------
    // Verify System Users page
    // -------------------------------------------------
    await userManagementPage.verifySystemUsersPage()


    // -------------------------------------------------
    // Open Add User
    // -------------------------------------------------
    await userManagementPage.openAddUserPage()


    await userManagementPage.addSystemUser({
        employeeName, username, password
    })

    // Verify created system user
    await userManagementPage.SearchAndverifySystemUser(username, employeeDisplayName)

    // --------------------------------------------------
    // Recruitment - Create Vacancy
    // --------------------------------------------------
    await dashboardPage.navigateToRecruitment()

    await recruitmentPage.verifyRecruitmentPage()

    await recruitmentPage.navigateToVacncies()

    await recruitmentPage.openAddVacancyPage()

    await recruitmentPage.addVacancy({
        vacancyName, jobTitle, description, hiringManager: employeeName, numberOfPositions
    })

    // Verify saved vacancy details on Edit Vacancy page
    await recruitmentPage.verifyVacancyDetails({
        vacancyName, jobTitle, description, hiringManager: employeeName, numberOfPositions
    })

    // --------------------------------------------------
    // Vacancies - Verify created vacancy
    // --------------------------------------------------
    await recruitmentPage.navigateBackToVacancies()

    await recruitmentPage.verifyVacancyInList(vacancyName, employeeDisplayName)


    // ==================================================
    // Recruitment - Create Candidate 
    // ==================================================
    await candidatePage.navigateToCandidates()

    await candidatePage.openAddCandidatePage()

    // Use the same vacncy created above
    await candidatePage.addCandidate({
        firstName: candidateFirstName,
        middleName: candidateMiddleName,
        lastName: candidateLastName,
        vacancy: vacancyName,
        email: candidateEmail,
        resumeUpload: resumePath
    })


    // ================================================
    // Candidate - Verify Application Stage 
    // ================================================
    await candidatePage.verifyApplicationStage({
        candidateName,
        vacancy: vacancyName,
        hiringManager: employeeName,
        status: 'Application Initiated'
    })


    // ================================================
    // Candidate - Verify Created Candidate 
    // ================================================
    await candidatePage.navigateBackToCandidates()

    await candidatePage.verifyCandidateInList({
        candidateName,
        vacancy: vacancyName,
        hiringManager: employeeName,
        status: 'Application Initiated'
    })
})