import { test, expect } from '@playwright/test'

import { LoginPage } from '../pages/LoginPage'
import { DashboardPage } from '../pages/DashboardPage'
import { PIMPage } from '../pages/PIMPage'

test('TC07 - Verify employee creation with login details and ESS authentication', async ({ page }) => {

    const loginPage = new LoginPage(page)
    const dashboardPage = new DashboardPage(page)
    const pimPage = new PIMPage(page)

    const firstName = 'Milo'
    const lastName = `ESS${Date.now().toString().slice(-4)}`
    const userName = `ess_user_${Date.now().toString().slice(-6)}`
    const password = 'Test@12345'
    const mismatchedPassword = 'Test@123456'

    const employeeDisplayName = `${firstName} ${lastName}`


    // --------------------------------------------------
    // 1. Login as Admin
    // --------------------------------------------------
    await page.goto('/', {
        waitUntil: 'domcontentloaded',
        timeout: 30000
    })

    await loginPage.login('Admin', 'admin123')

    await expect(page).toHaveURL(/\/dashboard\/index/, { timeout: 30000 })
    await expect(dashboardPage.dashboardHeading).toBeVisible({ timeout: 30000 })


    // --------------------------------------------------
    // 2. Navigate to PIM → Add Employee
    // --------------------------------------------------
    await pimPage.navigateToPIM()
    await pimPage.navigateToAddEmployee()


    // Employee ID is automatically generated by the application
    // when the Add Employee page is opened

    // --------------------------------------------------
    // 3. Enter First Name only
    // --------------------------------------------------
    await pimPage.firstName.fill(firstName)

    await expect(pimPage.firstName).toHaveValue(firstName)


    // --------------------------------------------------
    // 4. Trigger mandatory-field validation
    // --------------------------------------------------
    await pimPage.saveButton.click()

    await pimPage.verifyLastNameRequired()


    // --------------------------------------------------
    // 5. Correct Last Name
    // --------------------------------------------------
    await pimPage.enterLastName(lastName)


    // --------------------------------------------------
    // 6. Enable Create Login Details
    // --------------------------------------------------
    await pimPage.enableCreateLoginDetails()


    // --------------------------------------------------
    // 7. Verify default login configuration
    // --------------------------------------------------
    await pimPage.verifyLoginDetailsDefaults()


    // --------------------------------------------------
    // 8. Enter login details
    // --------------------------------------------------
    await pimPage.enterLoginDetails(userName, password, mismatchedPassword)


    // --------------------------------------------------
    // 9. Trigger password mismatch validation
    // --------------------------------------------------
    await pimPage.saveButton.click()

    await pimPage.verifyPasswordMismatch()


    // --------------------------------------------------
    // 10. Correct Confirm Password
    // --------------------------------------------------
    await pimPage.correctConfirmPassword(password)


    // --------------------------------------------------
    // 11. Create employee + ESS account
    // --------------------------------------------------
    await pimPage.saveNewEmployee()


    // --------------------------------------------------
    // 12. Verify employee creation
    // --------------------------------------------------
    await expect(pimPage.employeeFullName).toContainText(employeeDisplayName)

    await expect(pimPage.firstName).toHaveValue(firstName)
    await expect(pimPage.lastName).toHaveValue(lastName)


    // Employee ID is generated by the application
    const generatedEmployeeId = await pimPage.getEmployeeId()

    expect(generatedEmployeeId).toBeTruthy()


    // --------------------------------------------------
    // 13. Logout Admin
    // --------------------------------------------------
    await dashboardPage.logout()


    // --------------------------------------------------
    // 14. Login using newly created ESS credentials
    // --------------------------------------------------
    await loginPage.login(userName, password)


    // --------------------------------------------------
    // 15. Verify successful authentication
    // --------------------------------------------------
    await expect(dashboardPage.dashboardHeading).toBeVisible({ timeout: 30000 })


    // --------------------------------------------------
    // 16. Verify created account is the active user
    // --------------------------------------------------
    const userProfileName = page.locator('.oxd-userdropdown-name')

    await expect(userProfileName).toHaveText(employeeDisplayName, { timeout: 30000 })


    // --------------------------------------------------
    // 17. Verify Admin module is unavailable to ESS user
    // --------------------------------------------------
    const adminMenu = page.getByRole('link', { name: 'Admin', exact: true })

    await expect(adminMenu).toHaveCount(0)
})