import { test, expect } from '@playwright/test'

import { LoginPage } from '../pages/LoginPage'
import { DashboardPage } from '../pages/DashboardPage'
import { PIMPage } from '../pages/PIMPage'


// This scenario validates the complete employee lifecycle:
// create, retrieve, update, verify, delete, and confirm deletion.
test('TC03 - Verify user can create, update and delete an employee', async ({ page }) => {

    // Arrange: initialize the page objects needed for authentication and employee management.
    const loginPage = new LoginPage(page)
    const dashboardPage = new DashboardPage(page)
    const pimPage = new PIMPage(page)

    // Use dynamic values so the test does not collide with existing employee records in the system.
    const firstName = 'Reddy'
    const middleName = 'QA'
    const lastName = `Tester${Date.now()}`

    const employeeDetailsName = `${firstName} ${lastName}`

    // Act: open the application and sign in with admin credentials.
    await page.goto('/')
    await loginPage.login('Admin', 'admin123')

    // Assert: confirm the user has reached the dashboard after login.
    await expect(dashboardPage.dashboardHeading).toBeVisible()

    // Act: navigate to the PIM module and open the add-employee form.
    await pimPage.navigateToPIM()
    await expect(pimPage.pimHeading).toHaveText('PIM')

    await pimPage.navigateToAddEmployee()

    await pimPage.addNewEmployee(firstName, middleName, lastName)

    // Assert: verify the employee detail page shows the newly created person.
    await expect(pimPage.employeeFullName).toHaveText(employeeDetailsName)

    // Capture the Employee ID generated by the system.
    const generatedEmployeeId = await pimPage.getEmployeeId()

    // Act: return to the employee listing page
    await pimPage.navigateToEmployeeList()


    // Search for the newly created employee using the generated Employee ID
    await pimPage.searchEmployeeById(generatedEmployeeId)

    // Assert: confirm the created employee is present using the generated Employee ID.
    const newlyAddedEmployeeRow = await pimPage.findEmployeeById(generatedEmployeeId)

    expect(newlyAddedEmployeeRow).not.toBeNull()
    await expect(newlyAddedEmployeeRow).toBeVisible()

    // Open the created employee's details page for editing.
    await pimPage.editEmployee(newlyAddedEmployeeRow)


    // Validating the updated information of an employee on the employee details page after editing
    const updatedFirstName = `${firstName}2105`
    const updatedLastName = `${lastName}0200`

    // Act: update first and last name.
    await pimPage.updateEmployeeDetails({
        firstName: updatedFirstName,
        lastName: updatedLastName
    })

    // Assert: verify the updated values before saving.
    await expect(pimPage.firstName).toHaveValue(updatedFirstName)
    await expect(pimPage.middleName).toHaveValue(middleName)
    await expect(pimPage.lastName).toHaveValue(updatedLastName)


    // Update the employee informatio and save the changes on the employee details page
    await pimPage.saveEmployeeDetails()

    // Act: return to the employee listing page after updating the employee information
    await pimPage.navigateToEmployeeList()

    // After returnig to PIM by making changes to the employee, Search with the employee Id
    await pimPage.searchEmployeeById(generatedEmployeeId)

    // Retrieve the employee row using the Employee ID
    const updatedEmployeeRow = await pimPage.findEmployeeById(generatedEmployeeId)

    expect(updatedEmployeeRow).not.toBeNull()
    await expect(updatedEmployeeRow).toBeVisible()


    // Validate the updated employee details
    const cells = updatedEmployeeRow.locator('.oxd-table-cell')

    await expect(cells.nth(1)).toHaveText(generatedEmployeeId)
    await expect(cells.nth(2)).toHaveText(`${updatedFirstName} ${middleName}`)
    await expect(cells.nth(3)).toHaveText(updatedLastName)

    // Act: delete the same employee after completing the create and update lifecycle.
    await pimPage.deleteEmployee(updatedEmployeeRow)

    // Assert: verify the employee no longer exists.
    await pimPage.verifyEmployeDeleted(generatedEmployeeId)

})